// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9tgZok_LlpdAPofwiUCj3IxrhoKgEUlk',
    appId: '1:674536917590:web:d9cac1377c422f51b009f7',
    messagingSenderId: '674536917590',
    projectId: 'olx-clone-8d598',
    authDomain: 'olx-clone-8d598.firebaseapp.com',
    storageBucket: 'olx-clone-8d598.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOiikHQhKJzofbLWNTpILZDVvl1FBQwtQ',
    appId: '1:674536917590:android:390d7ecc7133b2cbb009f7',
    messagingSenderId: '674536917590',
    projectId: 'olx-clone-8d598',
    storageBucket: 'olx-clone-8d598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_ZeYc9HBfpBMxNobPazqneL6JnmtXQQ',
    appId: '1:674536917590:ios:079cd344b16bf06fb009f7',
    messagingSenderId: '674536917590',
    projectId: 'olx-clone-8d598',
    storageBucket: 'olx-clone-8d598.appspot.com',
    iosBundleId: 'com.example.olxClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_ZeYc9HBfpBMxNobPazqneL6JnmtXQQ',
    appId: '1:674536917590:ios:079cd344b16bf06fb009f7',
    messagingSenderId: '674536917590',
    projectId: 'olx-clone-8d598',
    storageBucket: 'olx-clone-8d598.appspot.com',
    iosBundleId: 'com.example.olxClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9tgZok_LlpdAPofwiUCj3IxrhoKgEUlk',
    appId: '1:674536917590:web:4e80ef979ab03d91b009f7',
    messagingSenderId: '674536917590',
    projectId: 'olx-clone-8d598',
    authDomain: 'olx-clone-8d598.firebaseapp.com',
    storageBucket: 'olx-clone-8d598.appspot.com',
  );
}
